<?php

/**
 * @file
 * whats_on.module
 */
function whats_on_movie_code() {
    $movie_ids =  db_select('node' , 'n')->fields('n', array('nid'))->condition('type' , 'films' , '=')->execute()->fetchAll();
    $film_id = array();
    foreach ($movie_ids as $key => $nid) {
        $node = node_load($nid->nid);
        $cineworld_id = $node->field_film_cineworld_id['und'][0]['value'];
        if ($cineworld_id) {
            $film_id[] = $cineworld_id;
        }
    }
    return $film_id;
}
function whats_on_cineworld() {
    $date = whats_on_cineworld_dates();
    $cinema = whats_on_cinema_id();
    $film = whats_on_movie_code();
    $times = whats_on_cineworld_times($cinema , $date , $film);
    $movie_times = drupal_http_request("http://www2.cineworld.co.uk/api/quickbook/performances?key=YEyQfFvY&cinema=78&film=160920&date=20150921");
    $time_request = array();
            if ($movie_times->code == 200):
                $data = drupal_json_decode($movie_times->data);
                foreach ($data as $key => $d) {
                    foreach ($d as $k => $times) {
                        if (!empty($times['time'])) :
                            $time_request[] = $times['time'];
                        endif;
                    }
                }
                whats_on_update_entity($time_request);
            endif;

}

/*
 * whats_on_cast Returns an array of casts
 *
 */
function whats_on_update_entity($times){
        if ($times) :
            foreach ($times as $key => $time) :
                $date = '20150929';
                $film = '160920';
                $cinema = '78';
                $node = node_load(704);
                $field_collection_value = entity_create('field_collection_item', array('field_name' => 'field_cinema_showing_times'));
                dsm($time);
                $field_collection_value->setHostEntity('node', $node);
               // dsm(entity_load('field_collection_item', array(762)));
                $field_collection_value->field_cinema_showing_date[LANGUAGE_NONE][0]['value'] = $time['date'];
                $field_collection_value->save();

                $field_collection_value_second = entity_create('field_collection_item', array('field_name' => 'field_cinema_time'));
                $field_collection_value_second->setHostEntity('node', $node);

                $time_format = strtotime($time['time']);
                //$time_format = date("H : i", $time_format);
                dsm($time_format);
                $field_collection_value_second->field_cinema_showing_time[LANGUAGE_NONE][0]['value'] = $time_format;
                $field_collection_value_second->save();
                // Save field-collection item.


                //  dsm($field_collection_value);
                //$node->field_film_cast[LANGUAGE_NONE][]['value'] = $field_collection_value->item_id;
                //  dsm($node);
            endforeach;

        else :
            drupal_set_message(t('Please give a valid node'));
        endif;

        return TRUE;
    }

function whats_on_cineworld_dates() {
    $film_codes = whats_on_movie_code();
    foreach ($film_codes as $film) {
        $movies = drupal_http_request("http://www2.cineworld.co.uk/api/quickbook/dates?key=YEyQfFvY&film=".$film);
        if ($movies->code == 200):
            // Decode our response
            $data = drupal_json_decode($movies->data);
            $dates = array();
            foreach ($data as $key => $date) {
                foreach ($date as $k => $d) {
                    $dates[] = $d;
                }
            }
            // If this is a movie return true;
            return $dates;
        endif;
    }
}
function whats_on_cineworld_times($cinema , $dates , $films) {
    foreach ($cinema as $cine) {
        $times[$cine] = array('film' => $films , 'dates' => $dates);
    }
    return $times;
}
function whats_on_cinema_id() {
    $cinema_ids = db_select('node' , 'n')->fields('n', array('nid'))->condition('type' , 'cinema' , '=')->execute()->fetchAll();
    $cinema_id = array();
    foreach ($cinema_ids as $key => $nid) {
        $node = node_load($nid->nid);
        $cinema_id[] = $node->field_cinema_id[LANGUAGE_NONE][0]['value'];
    }
    return $cinema_id;
}